/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.u1a4_li_jason;

/**
 *
 * @author 342360807
 */
public class StudentGrades extends javax.swing.JFrame {
    
    String [][] listt = new String [30][6];
    int index = 0;
    
    /**
     * Creates new form StudentGrades
     */
    public StudentGrades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        test1label = new javax.swing.JLabel();
        test2Label = new javax.swing.JLabel();
        test3Label = new javax.swing.JLabel();
        test4Label = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        test1Field = new javax.swing.JTextField();
        test2Field = new javax.swing.JTextField();
        test3Field = new javax.swing.JTextField();
        test4Field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();
        outputField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        studentAvgButton = new javax.swing.JButton();
        courseAvgButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 51, 51));
        titleLabel.setText("Student Grades");

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameLabel.setText("First Name:");

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastNameLabel.setText("Last Name:");

        test1label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        test1label.setText("Test 1:");

        test2Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        test2Label.setText("Test 2:");

        test3Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        test3Label.setText("Test 3:");

        test4Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        test4Label.setText("Test 4:");

        infoArea.setEditable(false);
        infoArea.setColumns(20);
        infoArea.setRows(5);
        jScrollPane1.setViewportView(infoArea);

        outputField.setEditable(false);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        studentAvgButton.setText("Student Average");
        studentAvgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentAvgButtonActionPerformed(evt);
            }
        });

        courseAvgButton.setText("Course Average");
        courseAvgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseAvgButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(test4Label)
                                    .addComponent(test1label)
                                    .addComponent(test2Label)
                                    .addComponent(test3Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(test4Field)
                                    .addComponent(test1Field)
                                    .addComponent(test2Field)
                                    .addComponent(test3Field))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lastNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(titleLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(studentAvgButton)
                        .addGap(18, 18, 18)
                        .addComponent(courseAvgButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(outputField, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(test1label)
                            .addComponent(test1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(test2Label)
                            .addComponent(test2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(test3Label)
                            .addComponent(test3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(test4Label)
                            .addComponent(test4Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(studentAvgButton)
                    .addComponent(courseAvgButton))
                .addGap(18, 18, 18)
                .addComponent(outputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        outputField.setText("");
        String firstName = firstNameField.getText(), lastName = lastNameField.getText(), test1 = test1Field.getText(), test2 = test2Field.getText(), test3 = test3Field.getText(), test4 = test4Field.getText(), nom = "";
        Boolean proceed = false;
        
        try{
            
            String arrayString = "";
            
            if (index != 30){
                if (!firstName.equals("") && !lastName.equals("")){
                    if (!test1.equals("") && !test2.equals("") && !test3.equals("") && !test4.equals("")){
                        double numTest1 = Double.parseDouble(test1), numTest2 = Double.parseDouble(test2), numTest3 = Double.parseDouble(test3), numTest4 = Double.parseDouble(test4);
                        if (numTest1 >= 0 && numTest2 >= 0 && numTest3 >= 0 && numTest4 >= 0){
                            if (index != 0){
                                for (int i = 0; i < index; i++){
                                    nom = listt[i][0] + listt[i][1];
                                    if (!nom.equals(firstName + lastName)){
                                        proceed = true;
                                    }
                                    else{
                                        proceed = false;
                                        outputField.setText("This student already exists.");
                                        firstNameField.setText("");
                                        lastNameField.setText("");
                                        break;
                                    }
                                }
                            }
                            else{
                                proceed = true;
                            }
                        }
                        else{
                            outputField.setText("Test results should be positive.");
                            test1Field.setText("");
                            test2Field.setText("");
                            test3Field.setText("");
                            test4Field.setText("");
                        }
                    }
                    else{
                        outputField.setText("Please enter a numeric grade for each test.");
                    }
                }
                else{
                    outputField.setText("Please enter a first and last name.");
                }
            }
            else{
                outputField.setText("The list is full, no one else can be added.");
                firstNameField.setText("");
                lastNameField.setText("");
                test1Field.setText("");
                test2Field.setText("");
                test3Field.setText("");
                test4Field.setText("");
            }
            
            if (proceed == true){
                listt[index][0] = firstName;
                listt[index][1] = lastName;
                listt[index][2] = test1;
                listt[index][3] = test2;
                listt[index][4] = test3;
                listt[index][5] = test4;
                index++;
                
                for (int i = 0; i < index; i++){
                    arrayString += "Student " + (i+1) + ": " + listt[i][0] + " " + listt[i][1] + "   ";
                    arrayString += "Grade 1: " + listt[i][2] + "%   ";
                    arrayString += "Grade 2: " + listt[i][3] + "%   ";
                    arrayString += "Grade 3: " + listt[i][4] + "%   ";
                    arrayString += "Grade 4: " + listt[i][5] + "%\n";
                    infoArea.setText(arrayString);
                }
            }
        }
        catch (Exception e){
            outputField.setText("You must enter a number for test results.");
            test1Field.setText("");
            test2Field.setText("");
            test3Field.setText("");
            test4Field.setText("");
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void studentAvgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentAvgButtonActionPerformed
        
        outputField.setText("");
        String firstName = firstNameField.getText(), lastName = lastNameField.getText(), sumString = "";
        boolean isThere = false;
        
        if (index != 0){
            if (!firstName.equals("") && !lastName.equals("")){
                for (int i = 0; i < index; i++){
                    if ((firstName + lastName).equals(listt[i][0] + listt[i][1])){
                        double g1 = Double.parseDouble(listt[i][2]), g2 = Double.parseDouble(listt[i][3]), g3 = Double.parseDouble(listt[i][4]), g4 = Double.parseDouble(listt[i][5]), sum = 0;
                        sum = g1 + g2 + g3 + g4;
                        sumString += (sum/4.0);
                        outputField.setText(firstName + " " + lastName + "'s average is " + sumString + "%");
                        isThere = true;
                        break;
                    }
                }
                if (isThere == false){
                    outputField.setText("This student is not on the list.");
                    firstNameField.setText("");
                    lastNameField.setText("");
                }
            }
            else{
                outputField.setText("Enter a name to find their average.");
            }
        }
        else{
            outputField.setText("The list is empty.");
        }
    }//GEN-LAST:event_studentAvgButtonActionPerformed

    private void courseAvgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseAvgButtonActionPerformed
        
        outputField.setText("");
        double avg = 0, counter = 0;
        
        if (index != 0){
            for (int i = 0; i < index; i++){
                for (int x = 2; x < 6; x++){
                    double temp = Double.parseDouble(listt[i][x]);
                    counter++;
                    avg += temp;
                }
            }
            avg /= counter;
            outputField.setText("The course average is " + avg + "%");
        }
        else{
            outputField.setText("The list is empty.");
        }
    }//GEN-LAST:event_courseAvgButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton courseAvgButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextArea infoArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField outputField;
    private javax.swing.JButton studentAvgButton;
    private javax.swing.JTextField test1Field;
    private javax.swing.JLabel test1label;
    private javax.swing.JTextField test2Field;
    private javax.swing.JLabel test2Label;
    private javax.swing.JTextField test3Field;
    private javax.swing.JLabel test3Label;
    private javax.swing.JTextField test4Field;
    private javax.swing.JLabel test4Label;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
